[build-system]
requires = ["maturin>=1.8,<2.0"]
build-backend = "maturin"

[project]
name = "leeson"
requires-python = ">=3.9"
dynamic = ["version"]

[tool.maturin]
features = ["python", "extension-module"]
module-name = "leeson"
